services:

  python:
    depends_on:
      db:
        condition: service_healthy
    build: ./app
    ports:
      - 8002:8002
    environment:
      - WAIT_HOSTS=db:5432

  db:
    image: postgres
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-U", "bewiseuser"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      PGUSER: bewiseuser
      POSTGRES_USER: bewiseuser
      POSTGRES_PASSWORD: bewisepassword

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080